services:
  postgres:
    image: postgres:16
    container_name: wordbattle-postgres
    environment:
      POSTGRES_DB: wordbattle
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:8.2.5-bookworm
    container_name: wordbattle-redis
    ports:
      - "6379:6379"