-- Kelime bankasi baslangic verisi. 155 kelime, 5 kategori.
--
-- ONEMLI: words tablosunu Hibernate olusturuyor (ddl-auto=update), bu yuzden
-- once uygulamayi bir kere calistirip tablolarin olusmasini beklemek gerekiyor.
-- Bos veritabaninda bu dosya "relation words does not exist" hatasi verir.
--
-- Calistirmak icin (container ayaktayken, backend/ klasorunden):
--   docker exec -i wordbattle-postgres psql -U postgres -d wordbattle < seed-words.sql
--
-- PowerShell'de < yonlendirmesi calismaz, bunun yerine:
--   Get-Content seed-words.sql -Raw | docker exec -i wordbattle-postgres psql -U postgres -d wordbattle
--
-- id sutunu varchar (Word.id String), bu yuzden gen_random_uuid() ::text ile cast ediliyor.
-- value alani unique oldugu icin tekrar calistirmak guvenli, mevcut kayitlar atlanir.

INSERT INTO words (id, value, category, difficulty) VALUES
-- ---------------------------------------------------------------- animals
(gen_random_uuid()::text, 'LION',        'animals', 'EASY'),
(gen_random_uuid()::text, 'TIGER',       'animals', 'EASY'),
(gen_random_uuid()::text, 'BEAR',        'animals', 'EASY'),
(gen_random_uuid()::text, 'WOLF',        'animals', 'EASY'),
(gen_random_uuid()::text, 'HORSE',       'animals', 'EASY'),
(gen_random_uuid()::text, 'RABBIT',      'animals', 'EASY'),
(gen_random_uuid()::text, 'MONKEY',      'animals', 'EASY'),
(gen_random_uuid()::text, 'EAGLE',       'animals', 'EASY'),
(gen_random_uuid()::text, 'SHARK',       'animals', 'EASY'),
(gen_random_uuid()::text, 'WHALE',       'animals', 'EASY'),
(gen_random_uuid()::text, 'ZEBRA',       'animals', 'EASY'),
(gen_random_uuid()::text, 'PANDA',       'animals', 'EASY'),
(gen_random_uuid()::text, 'CAMEL',       'animals', 'EASY'),
(gen_random_uuid()::text, 'TURTLE',      'animals', 'MEDIUM'),
(gen_random_uuid()::text, 'PARROT',      'animals', 'MEDIUM'),
(gen_random_uuid()::text, 'DONKEY',      'animals', 'MEDIUM'),
(gen_random_uuid()::text, 'FALCON',      'animals', 'MEDIUM'),
(gen_random_uuid()::text, 'ELEPHANT',    'animals', 'MEDIUM'),
(gen_random_uuid()::text, 'GIRAFFE',     'animals', 'MEDIUM'),
(gen_random_uuid()::text, 'DOLPHIN',     'animals', 'MEDIUM'),
(gen_random_uuid()::text, 'PENGUIN',     'animals', 'MEDIUM'),
(gen_random_uuid()::text, 'LEOPARD',     'animals', 'MEDIUM'),
(gen_random_uuid()::text, 'OCTOPUS',     'animals', 'MEDIUM'),
(gen_random_uuid()::text, 'LOBSTER',     'animals', 'MEDIUM'),
(gen_random_uuid()::text, 'OSTRICH',     'animals', 'MEDIUM'),
(gen_random_uuid()::text, 'SPARROW',     'animals', 'MEDIUM'),
(gen_random_uuid()::text, 'SQUIRREL',    'animals', 'MEDIUM'),
(gen_random_uuid()::text, 'KANGAROO',    'animals', 'HARD'),
(gen_random_uuid()::text, 'CROCODILE',   'animals', 'HARD'),
(gen_random_uuid()::text, 'BUTTERFLY',   'animals', 'HARD'),
(gen_random_uuid()::text, 'HEDGEHOG',    'animals', 'HARD'),
(gen_random_uuid()::text, 'JELLYFISH',   'animals', 'HARD'),
(gen_random_uuid()::text, 'SCORPION',    'animals', 'HARD'),
(gen_random_uuid()::text, 'RHINOCEROS',  'animals', 'HARD'),
(gen_random_uuid()::text, 'CHAMELEON',   'animals', 'HARD'),

-- ---------------------------------------------------------------- food
(gen_random_uuid()::text, 'APPLE',       'food', 'EASY'),
(gen_random_uuid()::text, 'BREAD',       'food', 'EASY'),
(gen_random_uuid()::text, 'CHEESE',      'food', 'EASY'),
(gen_random_uuid()::text, 'BANANA',      'food', 'EASY'),
(gen_random_uuid()::text, 'ORANGE',      'food', 'EASY'),
(gen_random_uuid()::text, 'TOMATO',      'food', 'EASY'),
(gen_random_uuid()::text, 'POTATO',      'food', 'EASY'),
(gen_random_uuid()::text, 'CARROT',      'food', 'EASY'),
(gen_random_uuid()::text, 'PEPPER',      'food', 'EASY'),
(gen_random_uuid()::text, 'HONEY',       'food', 'EASY'),
(gen_random_uuid()::text, 'BUTTER',      'food', 'EASY'),
(gen_random_uuid()::text, 'SUGAR',       'food', 'EASY'),
(gen_random_uuid()::text, 'LEMON',       'food', 'EASY'),
(gen_random_uuid()::text, 'CHERRY',      'food', 'EASY'),
(gen_random_uuid()::text, 'ONION',       'food', 'EASY'),
(gen_random_uuid()::text, 'YOGURT',      'food', 'MEDIUM'),
(gen_random_uuid()::text, 'GARLIC',      'food', 'MEDIUM'),
(gen_random_uuid()::text, 'NOODLE',      'food', 'MEDIUM'),
(gen_random_uuid()::text, 'ALMOND',      'food', 'MEDIUM'),
(gen_random_uuid()::text, 'WALNUT',      'food', 'MEDIUM'),
(gen_random_uuid()::text, 'BISCUIT',     'food', 'MEDIUM'),
(gen_random_uuid()::text, 'SAUSAGE',     'food', 'MEDIUM'),
(gen_random_uuid()::text, 'PANCAKE',     'food', 'MEDIUM'),
(gen_random_uuid()::text, 'LETTUCE',     'food', 'MEDIUM'),
(gen_random_uuid()::text, 'AVOCADO',     'food', 'MEDIUM'),
(gen_random_uuid()::text, 'MUSHROOM',    'food', 'MEDIUM'),
(gen_random_uuid()::text, 'SANDWICH',    'food', 'MEDIUM'),
(gen_random_uuid()::text, 'CUCUMBER',    'food', 'MEDIUM'),
(gen_random_uuid()::text, 'CINNAMON',    'food', 'HARD'),
(gen_random_uuid()::text, 'OMELETTE',    'food', 'HARD'),
(gen_random_uuid()::text, 'CHOCOLATE',   'food', 'HARD'),
(gen_random_uuid()::text, 'SPAGHETTI',   'food', 'HARD'),
(gen_random_uuid()::text, 'STRAWBERRY',  'food', 'HARD'),
(gen_random_uuid()::text, 'PINEAPPLE',   'food', 'HARD'),
(gen_random_uuid()::text, 'WATERMELON',  'food', 'HARD'),

-- ---------------------------------------------------------------- colors
(gen_random_uuid()::text, 'RED',         'colors', 'EASY'),
(gen_random_uuid()::text, 'BLUE',        'colors', 'EASY'),
(gen_random_uuid()::text, 'GREEN',       'colors', 'EASY'),
(gen_random_uuid()::text, 'BLACK',       'colors', 'EASY'),
(gen_random_uuid()::text, 'WHITE',       'colors', 'EASY'),
(gen_random_uuid()::text, 'BROWN',       'colors', 'EASY'),
(gen_random_uuid()::text, 'PINK',        'colors', 'EASY'),
(gen_random_uuid()::text, 'GREY',        'colors', 'EASY'),
(gen_random_uuid()::text, 'YELLOW',      'colors', 'EASY'),
(gen_random_uuid()::text, 'PURPLE',      'colors', 'MEDIUM'),
(gen_random_uuid()::text, 'GOLDEN',      'colors', 'MEDIUM'),
(gen_random_uuid()::text, 'SILVER',      'colors', 'MEDIUM'),
(gen_random_uuid()::text, 'MAROON',      'colors', 'MEDIUM'),
(gen_random_uuid()::text, 'BEIGE',       'colors', 'MEDIUM'),
(gen_random_uuid()::text, 'INDIGO',      'colors', 'MEDIUM'),
(gen_random_uuid()::text, 'SCARLET',     'colors', 'HARD'),
(gen_random_uuid()::text, 'CRIMSON',     'colors', 'HARD'),
(gen_random_uuid()::text, 'MAGENTA',     'colors', 'HARD'),
(gen_random_uuid()::text, 'LAVENDER',    'colors', 'HARD'),
(gen_random_uuid()::text, 'TURQUOISE',   'colors', 'HARD'),

-- ---------------------------------------------------------------- objects
(gen_random_uuid()::text, 'MIRROR',      'objects', 'EASY'),
(gen_random_uuid()::text, 'WINDOW',      'objects', 'EASY'),
(gen_random_uuid()::text, 'LADDER',      'objects', 'EASY'),
(gen_random_uuid()::text, 'CANDLE',      'objects', 'EASY'),
(gen_random_uuid()::text, 'BUCKET',      'objects', 'EASY'),
(gen_random_uuid()::text, 'HAMMER',      'objects', 'EASY'),
(gen_random_uuid()::text, 'PILLOW',      'objects', 'EASY'),
(gen_random_uuid()::text, 'CAMERA',      'objects', 'EASY'),
(gen_random_uuid()::text, 'GUITAR',      'objects', 'EASY'),
(gen_random_uuid()::text, 'PIANO',       'objects', 'EASY'),
(gen_random_uuid()::text, 'DRAWER',      'objects', 'EASY'),
(gen_random_uuid()::text, 'ANCHOR',      'objects', 'MEDIUM'),
(gen_random_uuid()::text, 'VIOLIN',      'objects', 'MEDIUM'),
(gen_random_uuid()::text, 'TROPHY',      'objects', 'MEDIUM'),
(gen_random_uuid()::text, 'BLANKET',     'objects', 'MEDIUM'),
(gen_random_uuid()::text, 'WHISTLE',     'objects', 'MEDIUM'),
(gen_random_uuid()::text, 'COMPASS',     'objects', 'MEDIUM'),
(gen_random_uuid()::text, 'CURTAIN',     'objects', 'MEDIUM'),
(gen_random_uuid()::text, 'TROLLEY',     'objects', 'MEDIUM'),
(gen_random_uuid()::text, 'LANTERN',     'objects', 'MEDIUM'),
(gen_random_uuid()::text, 'KEYBOARD',    'objects', 'MEDIUM'),
(gen_random_uuid()::text, 'UMBRELLA',    'objects', 'MEDIUM'),
(gen_random_uuid()::text, 'SCISSORS',    'objects', 'MEDIUM'),
(gen_random_uuid()::text, 'BICYCLE',     'objects', 'MEDIUM'),
(gen_random_uuid()::text, 'ENVELOPE',    'objects', 'MEDIUM'),
(gen_random_uuid()::text, 'BACKPACK',    'objects', 'MEDIUM'),
(gen_random_uuid()::text, 'SUITCASE',    'objects', 'MEDIUM'),
(gen_random_uuid()::text, 'CALENDAR',    'objects', 'MEDIUM'),
(gen_random_uuid()::text, 'WARDROBE',    'objects', 'HARD'),
(gen_random_uuid()::text, 'NECKLACE',    'objects', 'HARD'),
(gen_random_uuid()::text, 'TELESCOPE',   'objects', 'HARD'),
(gen_random_uuid()::text, 'TELEPHONE',   'objects', 'HARD'),
(gen_random_uuid()::text, 'MICROSCOPE',  'objects', 'HARD'),
(gen_random_uuid()::text, 'TYPEWRITER',  'objects', 'HARD'),
(gen_random_uuid()::text, 'REFRIGERATOR','objects', 'HARD'),

-- ---------------------------------------------------------------- nature
(gen_random_uuid()::text, 'RIVER',       'nature', 'EASY'),
(gen_random_uuid()::text, 'OCEAN',       'nature', 'EASY'),
(gen_random_uuid()::text, 'FOREST',      'nature', 'EASY'),
(gen_random_uuid()::text, 'DESERT',      'nature', 'EASY'),
(gen_random_uuid()::text, 'ISLAND',      'nature', 'EASY'),
(gen_random_uuid()::text, 'VALLEY',      'nature', 'EASY'),
(gen_random_uuid()::text, 'SUNSET',      'nature', 'EASY'),
(gen_random_uuid()::text, 'STORM',       'nature', 'EASY'),
(gen_random_uuid()::text, 'BREEZE',      'nature', 'MEDIUM'),
(gen_random_uuid()::text, 'CANYON',      'nature', 'MEDIUM'),
(gen_random_uuid()::text, 'MEADOW',      'nature', 'MEDIUM'),
(gen_random_uuid()::text, 'SWAMP',       'nature', 'MEDIUM'),
(gen_random_uuid()::text, 'TUNDRA',      'nature', 'MEDIUM'),
(gen_random_uuid()::text, 'CAVERN',      'nature', 'MEDIUM'),
(gen_random_uuid()::text, 'GLACIER',     'nature', 'MEDIUM'),
(gen_random_uuid()::text, 'THUNDER',     'nature', 'MEDIUM'),
(gen_random_uuid()::text, 'RAINBOW',     'nature', 'MEDIUM'),
(gen_random_uuid()::text, 'VOLCANO',     'nature', 'MEDIUM'),
(gen_random_uuid()::text, 'HORIZON',     'nature', 'MEDIUM'),
(gen_random_uuid()::text, 'BLOSSOM',     'nature', 'MEDIUM'),
(gen_random_uuid()::text, 'HARVEST',     'nature', 'MEDIUM'),
(gen_random_uuid()::text, 'DRIZZLE',     'nature', 'MEDIUM'),
(gen_random_uuid()::text, 'PRAIRIE',     'nature', 'MEDIUM'),
(gen_random_uuid()::text, 'MOUNTAIN',    'nature', 'MEDIUM'),
(gen_random_uuid()::text, 'TWILIGHT',    'nature', 'HARD'),
(gen_random_uuid()::text, 'LIGHTNING',   'nature', 'HARD'),
(gen_random_uuid()::text, 'WATERFALL',   'nature', 'HARD'),
(gen_random_uuid()::text, 'AVALANCHE',   'nature', 'HARD'),
(gen_random_uuid()::text, 'EARTHQUAKE',  'nature', 'HARD'),
(gen_random_uuid()::text, 'WILDERNESS',  'nature', 'HARD')
ON CONFLICT (value) DO NOTHING;
